<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE directory [
        <!ELEMENT name EMPTY>
        <!ELEMENT address EMPTY>
        <!ELEMENT number EMPTY>
        <!ELEMENT contact (name, address, number)>
        <!ELEMENT records (contact*)>
        <!ELEMENT directory (records*)>

        <!ATTLIST name
                first CDATA #REQUIRED
                last  CDATA #REQUIRED
                >
        <!ATTLIST address
                home CDATA #REQUIRED
                work  CDATA #REQUIRED
                >

        <!ATTLIST number
                home CDATA #REQUIRED
                work  CDATA #REQUIRED
                >
]>

<directory>
    <records>
        <contact>
            <name first="Rowan" last="Gill"/>
            <address home="London" work="New York"/>
            <number home="+1-532-521-23" work="+1-533-654-12"/>
        </contact>
        <contact>
            <name first="Harley" last="Gibson"/>
            <address home="Denver" work="Denver"/>
            <number home="+1-331-521-77" work="+1-939-654-32"/>
        </contact>
        <contact>
            <name first="Ashley" last="Evans"/>
            <address home="Waterville" work="Bedford"/>
            <number home="+1-831-521-10" work="+1-144-654-65"/>
        </contact>
    </records>
</directory>